### ISSUE TITLE
Unable to update ... because of unknow network interruption

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#1]
Trying

```
Downloads/AppImageUpdater-77e112e-x86_64.AppImage /isodevice/Applications/appimagetool-x86_64.AppImage
```

Getting

> Unable to update appimagetool-x86_64.AppImage because of unknow network interruption

![fail](https://user-images.githubusercontent.com/2480569/34905840-7267efd4-f861-11e7-8541-2f4469991da6.png)

Additional information:

```
strings /isodevice/Applications/appimagetool-x86_64.AppImage | grep zsyǹc
zsync|https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage.zsync
```

**Comment by antony-jr** [comment]
I never tested **Direct Zsync  URL** before , could you point some examples that I can use ?

**Comment by probonopd** [comment]
It is documented here: 
https://github.com/AppImage/AppImageSpec/blob/master/draft.md#zsync-1

**Comment by probonopd** [comment]
In case you encounter a type of update information unknown to the updater (the string before the first "|"), the updater should tell that it encountered an "unknown type of update information", and offer to update itself (the updater).

**Comment by antony-jr** [comment]
@probonopd the **Bridge** handles it well , but I don't have any examples to test it out , could you provide some **AppImages** which uses Direct Zsync URL.

**Comment by probonopd** [comment]
Attaching one here (zipped because GitHub Issues doesn't allow for other file type attachments).

[appimagetool-x86_64.AppImage.zip](https://github.com/antony-jr/AppImageUpdater/files/1628312/appimagetool-x86_64.AppImage.zip)

**Comment by antony-jr** [comment]
Thanks! ❤️

**Comment by antony-jr** [comment]
@probonopd The error most likely will be with **OpenSSL** beign a wrong version from the  Qt Built Version.

**Comment by antony-jr** [comment]
Must be patched now , Please refer https://github.com/antony-jr/AppImageUpdater/commit/082ea8d52b06f0b0655bb993a6a19f0c648d7fb3 for more information , If the problem still exists , reopen this issue! Thank You! 👍

**Comment by antony-jr** [comment]
Everything seems to work but github does not allow **HEAD** ( or prehaps **Amazon S3** does not , because the request type and **HMAC** is checked { Which the HMAC always points to a **GET** request! ) and so **HEAD** fails.

# Solution 
* Completely strip **HEAD** requests and use **RAW GET** with limiting mechanism ( not recommended but considering a handfull of webservers , I think we should only work with **GET**)
