### ISSUE TITLE
Minimalistic design

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#10]
Of course design is a subjective subject, so it's entirely up to you - but I think it would greatly help the adoption of the updater if it would look as minimalistic, "generic" as possible, trying to blend in with the native theme of Qt/the system rather than using bold/dark colors, large/custom fonts and such.

For example, the [Sparkle framework](https://sparkle-project.org/) is carefully designed to look as "native" and unobtrusive as possible on macOS:

![checking_for_updates-100644286-large](https://user-images.githubusercontent.com/2480569/34955316-c406207a-fa1b-11e7-8cee-fbe7d2573e4e.jpg)

This feels "seamless", "straightforward", and "lightweight" to me, and basically looks like it was coming from the system. If I was an application author, I would want this minimalistic and unobtrusive kind of "native" look for the updater.

Note that it does not say ".app .dmg Updater" or something like that, because that are technical details normal users are not interested in. Likewise, we do not need to say "AppImage Updater" or anything like that, just "Updating Subsurface", "Checking for updates...", etc. Also, I like how they use the application icon to make the updater look like a part of the application.

**Comment by antony-jr** [comment]
I really care about the UI more.

**Comment by antony-jr** [comment]
but @probonopd this is just an example , do we really need to redesign this , lets just use this to test out the new libappimageupdate for Qt , Aka **AppImageUpdaterBridge**. To Fix bugs and other stuff , I am building a plugin too, I created this to find flaws in **AppImageUpdaterBridge** and it really does **had** a lot ( fixed now , mostly ).
My main design would be the plugin or the end result which we are aiming at.  what do you think ?

Lets just keep this a cool app to checkout AppImageUpdater Bridge and also help developers understand it more.
