### ISSUE TITLE
GUI for updating all AppImages inside a directory

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#13]
GUI should be changed for updating all AppImages inside a directory - currently this is what happens:

![screenshot](https://user-images.githubusercontent.com/2480569/44959381-c0791900-aedc-11e8-80c2-158a1bc79f13.png)

**Comment by antony-jr** [comment]
Oh! That looks awful , I will fix that soon as possible!

**Comment by antony-jr** [comment]
I am also planning for a no confirm checkbox to just update AppImages without the confirmation dialog which is quite awful when it comes to large scale updating. Also include a background update model.
