### ISSUE TITLE
Automatically elevate to root if necessary

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#14]
Same as https://github.com/AppImage/AppImageUpdate/issues/1

![permissions](https://user-images.githubusercontent.com/2480569/44959389-e0a8d800-aedc-11e8-8dca-f3fe5ba64dcf.png)

Please see how e.g., the Etcher AppImage solves this.

**Comment by antony-jr** [comment]
I know how to solve this but didn't give the priority for that , I hope the log should give information on permission errors too. I will fix this soon.

**Comment by antony-jr** [comment]
@probonopd This is the latest version which has automatic root elevation  , strictly hard coded with the sudo command , I hope modern linux distro's will have sudo installed.

https://youtu.be/2tfrU_s72zA

Also , Now the error dialog box should have a layperson friendly error message for all errors including network errors.

**Sorry for the shutters in the video , My graphics card is low powered.**

**Comment by probonopd** [comment]
Thank you very much, highly appreciated @antony-jr

**Comment by probonopd** [comment]
A special case of this issue still exists: If one tries to update such a file, and there is _no_ newer version on the server, we get:

![error](https://user-images.githubusercontent.com/2480569/68623755-209a2080-04cd-11ea-95db-a57167c1929b.png)

**Comment by antony-jr** [comment]
Actually I did not include the authorization for the standalone dialog, will do it ASAP.

**Comment by probonopd** [comment]
Please reopen. Thanks.

**Comment by antony-jr** [comment]
Show be fixed in the latest version.

**Comment by probonopd** [comment]
Thank you very much @antony-jr, this makes a big difference for me :+1:
