### ISSUE TITLE
AppImage not updating properly

### ISSUE THREAD

**Issue by antony-jr** [antony-jr/AppImageUpdater#16]
As seen in https://github.com/AppImage/AppImageUpdate/issues/128#issuecomment-519061086

**CC**: @luzpaz 

Lets do any further discussions here to keep everything organized.

**Comment by luzpaz** [comment]
:+1:

**Comment by antony-jr** [comment]
So did you actually restart the application when you did the update?

**Comment by luzpaz** [comment]
hmm... I may have not

**EDIT**: will do that now

**Comment by antony-jr** [comment]
Because I think its a bug in the library such that when a error occurs all slots are just screwed, I have to fix that ASAP.

**Comment by luzpaz** [comment]
@antony-jr i just reran and it zipped through the download but now it hanging at 100% again (an aside: oddly it shows `Updating 371 MiB of 363 Mib` where before it showed 369 of 363 if you recall. Just thought I'd mention that)

**Comment by antony-jr** [comment]
But did the update succeed?

EDIT: any error dialog box?

**Comment by luzpaz** [comment]
no error but not sure how to see if succeeded. the log is similar to previous time.. just stops short of showing anything useful

**Comment by antony-jr** [comment]
Hmm... Looks like a serious one.

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/62621185-4bcb0d80-b8e9-11e9-929c-b380eb2d3ff4.png)  
Here's what I see (same as before)

**Comment by luzpaz** [comment]
@antony-jr also note that pressing cancel will not affect anything. ~I need to ctrl+c in the CLI to kill the application~

**EDIT:** Actually that's not true. I just needed to close the dialog window.

**Comment by antony-jr** [comment]
Do you have qmake? dev-tools to compile Qt applications? If so then you can try compiling the example programs present in the library. https://github.com/antony-jr/AppImageUpdaterBridge and can test running the updater. Because this bug may be of AppImageUpdater and not the library.

```
 $ git clone https://github.com/antony-jr/AppImageUpdaterBridge
 $ cd AppImageUpdaterBridge
 $ cd examples/SimpleUpdateGUI
 $ mkdir build 
 $ cd build
 $ qmake ..
 $ make -j$(nproc)
 $ ./SimpleUpdateGUI [PATH TO APPIMAGE YOU WANT TO UPDATE]
```

**Comment by luzpaz** [comment]
```
$qmake --version
QMake version 3.1
Using Qt version 5.13.0 in /usr/lib
```
Is that OK ?

**Comment by antony-jr** [comment]
Yep that's all you need.

I assume you are using KDE?

**Comment by luzpaz** [comment]
Nope, Xfce

**Comment by luzpaz** [comment]
Ok, built SimpleUpdateGui and now retesting:  
It got to 100% but is hanging again :cry:

**Comment by luzpaz** [comment]
...still hanging

**Comment by antony-jr** [comment]
If you have time please upload the AppImage you are trying to update to https://transfer.sh or any other services and share the link.

**Comment by antony-jr** [comment]
I can really use your mysterious AppImage to stress test the library in future.

**Comment by luzpaz** [comment]
uploading now to transfer.sh will post link when it's done.  
FYI, i got an error back finally:  
![image](https://user-images.githubusercontent.com/4140247/62622196-c09f4700-b8eb-11e9-8db2-23a8260c3967.png)

**Comment by luzpaz** [comment]
https://transfer.sh/rkaMF/FreeCAD_0.19-17499-Linux-Conda_Py3Qt5_glibc2.12-x86_64.AppImage

**Comment by antony-jr** [comment]
Thank you so much.

**Comment by antony-jr** [comment]
![Screenshot_20190807_182958](https://user-images.githubusercontent.com/33930174/62624795-7ea0f000-b941-11e9-98a3-ce30c072c772.png)


**Its so weird on my end the update finishes successfully.** I think this issue occurs if you have slow internet connection????? What is your internet connection speed by the way. 

Mine is **~2 Mega bytes per second(20 mega bit per second as given by ISP)**

Anyways @luzpaz Thanks for your time. I will try my best to mimic your issue.

**Comment by antony-jr** [comment]
@luzpaz I got the error, 
![Screenshot_20190807_183910](https://user-images.githubusercontent.com/33930174/62625455-dab84400-b942-11e9-91dd-7e40583ff013.png)

**Comment by antony-jr** [comment]
I will try implementing multiple range requests and try this again. Also I am gonna give some intervals between each request and response to make it easy on the server.

**Comment by antony-jr** [comment]
Hopefully this will be fixed... If not please reopen this. But this time I guess the program won't hang but gives a concise error message.
