### ISSUE TITLE
Add a flag to auto-accept dialogs if triggered with --standalone-update-dialog

### ISSUE THREAD

**Issue by luzpaz** [antony-jr/AppImageUpdater#18]
It would be nice to have the ability to invoke AppImageUpdater from the CLI and pass the AppImage that you want it to update.
Usecase:  
`$ ./AppImageUpdater.AppImage FreeCAD_0.19-18614.AppImage`

Bonus: add a flag that automatically quits AppImageUpdater after it successfully completes its task.

**Comment by luzpaz** [comment]
Sorry, didn't notice the `--standalone-update-dialog`

**Comment by antony-jr** [comment]
it was not documented on purpose. It was used privately by the program to update AppImages with root access. But I guess you can use it if you want. It does not have the name fix in it though.(for now)

**Comment by luzpaz** [comment]
Is it possible to add flags that will bypass the dialogs ?

**Comment by antony-jr** [comment]
> Is it possible to add flags that will bypass the dialogs ?

Yes we can. You can actually do that in the settings of the main Application but the standalone dialog box does not respect that so we would definitely need a flag from the command line. I'm busy right now, So this is gonna take some time.

**Comment by luzpaz** [comment]
No rush. Thanks!

**Comment by probonopd** [comment]
I was about to ask for the exact same thing. Would be greatly appreciated! :+1: 

* One mode where one can launch AppImageUpdater with an AppImage as its argument so that the changelog dialog shows -- I learn here that this actually is already implemented with `--standalone-update-dialog`
* Another mode where one can launch AppImageUpdater with an AppImage as its argument so that the update directly starts with no further things to click

In both modes, there should no desktop notifications and no status bar plugin/widget, and AppImageUpdater should quit after the updating is done.

Thank you.

**Comment by antony-jr** [comment]
Okay the latest build has the following options,
```
[antonyjr@Liz AppImages]$ ./AppImageUpdater-7420c48-x86_64.AppImage --help
Usage: ./AppImageUpdater-7420c48-x86_64.AppImage [options]
A Simple Program to Update the AppImage format using Zsync Algorithm.

Options:
  -h, --help                                 Displays this help.
  -v, --version                              Displays version information.
  --minimized                                Start the Application minimized.
  --noconfirm, -n                            Automatically accept all
                                             confirmations in standalone mode.
  --silent, -s                               Show minimum number of dialogs in
                                             standalone mode.
  --standalone-update-dialog, -d <AppImage>  Update a <AppImage> with nothing
                                             but a AppImageUpdater update
                                             dialog.
```

Is this okay with y'all?



> In both modes, there should no desktop notifications and no status bar plugin/widget, and AppImageUpdater should quit after the updating is done.

By default it does the above mentioned. I think you did not close the previous applications properly(*Clicking on the 'X' in the title bar will not close it, you have to click on the exit button in the application*). **In the past the application did not implement the context menu for the tray icon so I think you were not able to close it, but now its been implemented, you should force kill any previous version that are running in the background and try the new one.**

**Comment by probonopd** [comment]
Thanks for implementing. Graet work :+1: 

Question: Which of these can/cannot be used together?

```
  --noconfirm, -n                            Automatically accept all
                                             confirmations in standalone mode.
  --silent, -s                               Show minimum number of dialogs in
                                             standalone mode.
  --standalone-update-dialog, -d <AppImage>  Update a <AppImage> with nothing
                                             but a AppImageUpdater update
                                             dialog.

```

From experimenting, the combination `-n -d` implements

> Another mode where one can launch AppImageUpdater with an AppImage as its argument so that the update directly starts with no further things to click

Maybe it could be clarified in the help text.

Thank you very much for this.

**Comment by luzpaz** [comment]
I understood `-d` to be an alternate short form of `  --standalone-update-dialog`. I'm on mobile right now so I can't test.

**Comment by probonopd** [comment]
Yes it was my mistake, edited above.

**Comment by probonopd** [comment]
Maybe there should also be a way to suppress this dialog:

> Update completed successfully for AppImageUpdater-9b4000e-x86_64.AppImage, the new version is saved at '/home/me/test/AppImageUpdater-7420c48-x86_64-revised-on-2019-11-10T13-36-37.AppImage', do you want to open it?

**Comment by luzpaz** [comment]
can there be an `-s`-like option for the CLI ? where the debug log output is suppressed ? Should I open a new ticket for that?

**Comment by probonopd** [comment]
Actually I think the output should only be shown on the command line if requested with `--verbose` or `--debug`... except for errors.

**Comment by antony-jr** [comment]
> Maybe there should also be a way to suppress this dialog:
>> Update completed successfully for AppImageUpdater-9b4000e-x86_64.AppImage, the new version is saved at '/home/me/test/AppImageUpdater-7420c48-x86_64-revised-on-2019-11-10T13-36-37.AppImage', do you want to open it?


@probonopd Then how can you know if a update is completed successfully, **Do you want a command line tool?** If so why can't you use a command line tool like the official one?


> Question: Which of these can/cannot be used together?

You can use all the things together. ```-n``` for no confirm. ```-s``` to show minimum no. of dialogs. ```-d``` to give the actual AppImage to update.

When using ```-s```, No progress dialog will be shown and No checking for update dialog will be shown. But error dialogs and final update notification will be shown(that is the update completed dialog).

When using ```-n```, Only the confirmation dialog will be auto accepted but all other dialogs will be shown normally.

> can there be an -s-like option for the CLI ? where the debug log output is suppressed ? Should I open a new ticket for that?

@luzpaz Yep. I think so too. I will add a verbose mode and hide all logs by default as suggested.


**If you want a CLI tool then I can make a separate one for that which is much better at displaying information CLI friendly. Do you want a command line tool?**

**Comment by luzpaz** [comment]
a CLI tool would be awesome, yes

**Comment by probonopd** [comment]
Personally I was not looking for a command line tool, I am trying to integrate the updater with an experimental version of appimaged that I am re-writing from scratch in Go (Golang). It can update AppImages by right-clicking on them, and I want to invoke AppImageUpdater. But now I can do that, so it's fine.

**Comment by probonopd** [comment]
I am using `-n -d <...>`. If the AppImage cannot be updated due to an error, then unfortunately no error dialog is shown in _some_ cases.

In other cases it does show the dialog:

![](https://user-images.githubusercontent.com/2480569/68624269-60add300-04ce-11ea-8c7b-b021ee87a3f0.png)

Actually it shows more than one dialog for just one AppImage:

![](https://user-images.githubusercontent.com/2480569/68624367-8aff9080-04ce-11ea-8f22-f259052b0196.png)

If the AppImage is already the newest version, then an information is shown.

**Comment by antony-jr** [comment]
> I am using -n -d <...>. If the AppImage cannot be updated due to an error, then unfortunately no error dialog is shown in some cases.

Try the latest version, it should be fixed.


No we have new usage options,

```
Options:
  -h, --help                                 Displays this help.
  -v, --version                              Displays version information.
  --minimized                                Start the Application minimized.
  --noconfirm, -n                            Automatically accept all
                                             confirmations in standalone mode.
  --silent, -s                               Show minimum number of dialogs in
                                             standalone mode.
  --show-checking-for-update-dialog, -c      Show Checking for update dialog in
                                             standalone mode.
  --standalone-update-dialog, -d <AppImage>  Update a <AppImage> with nothing
                                             but a AppImageUpdater update
                                             dialog.
```

**Now the 'checking for update dialog' will not be shown unless you explicitly mention the ```-c``` option**.

So Use,

```-s``` - To hide the progress dialog.
```-d``` - To give the path to appimage
```-c``` - To Show the *Checking for Update* dialog, **avoid this option if you don't want to show it**.
```-n``` - Do not show the update available dialog(i.e The change log window) and say yes to install update

@probonopd is this okay?

**Comment by probonopd** [comment]
Perfect :+1:
