### ISSUE TITLE
Get rid of the application indicators?

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#19]
These "i" icons are added by AppImageUpdater to my menu bar and do absolutely nothing on my Xfce system. When I click on them, nothing happens. Right-click gives me Xfce's option to remove them. Personally I find them (and desktop notifications) rather annoying.

![](https://user-images.githubusercontent.com/2480569/68538612-4a3d3580-036f-11ea-8e43-18b58054ac31.png)

What do others think? Maybe I am missing how these things are adding value?

This is on Xubuntu 18.04, where these things are managed by:

![](https://user-images.githubusercontent.com/2480569/68538632-8bcde080-036f-11ea-8edd-d4e3e93a7420.png)

**Comment by antony-jr** [comment]
> These "i" icons are added by AppImageUpdater to my menu bar and do absolutely nothing on my Xfce system. When I click on them, nothing happens. Right-click gives me Xfce's option to remove them. Personally I find them (and desktop notifications) rather annoying.

The *i* icons are indeed added by the application but the icon was modified by Xfce. **Initially when the application starts it behaves normally as it would do in my DE but after seconds it just turns into the mysterious 'i' icon**. *The application tray icon also works great when using it in root mode*.

![Screenshot_2019-11-10_09-18-46](https://user-images.githubusercontent.com/33930174/68541880-f2341c80-03ca-11ea-9e38-1ed176f1d566.png)

Also now I've added a context menu which will appear if you click the 'i' icon,

![icn](https://user-images.githubusercontent.com/33930174/68541902-5f47b200-03cb-11ea-9c35-c78bfb269f8b.png)


> What do others think? Maybe I am missing how these things are adding value?

Honestly I don't know what others think. 


This is my use case,

**In my DE, the updater minimizes to the tray and just clicking on the tray icon would show the updater, So I would just browse through my file explorer and when I see an AppImage I want to update, I just open the updater from tray icon and drag the appimage(which then queues for update) and close the updater which minimizes to the tray again. Update confirmation is shown when required(If this is disabled in the settings, nothing appears and only the final dialog box appears)**

**Comment by antony-jr** [comment]
I've been thinking about redesigning the updater like a torrent client. You can add Appimage you want to update and it is updated as if the torrent client is downloading the file. You can also pause the update and stuff like that. You can also add options when you start the update like execute certain command when you finish update. *But I think this design is an overkill.*

**Comment by probonopd** [comment]
Thanks @antony-jr for your explanation. Personally I like "minimalism". As Dieter Rams, a famous German designer who influenced the later Apple design once said,

> Good design is as little design as possible. Less, but better – because it concentrates on the essential aspects, and the products are not burdened with non-essentials. Back to purity, back to simplicity. 

Source: https://www.interaction-design.org/literature/article/dieter-rams-10-timeless-commandments-for-good-design

For example I think the minimal but good design of https://sparkle-project.org/ makes it so attractive on the Mac.

So my 2 cent, I personally think less is more here, and an updater should be as simple and unobtrusive as possible for a user, and not offer any confusing choices.

**Comment by probonopd** [comment]
I can confirm that I can now at least show and quit the application from there. Thanks for fixing.
