### ISSUE TITLE
CLI capability

### ISSUE THREAD

**Issue by luzpaz** [antony-jr/AppImageUpdater#21]
Separating this out of https://github.com/antony-jr/AppImageUpdater/issues/18#issuecomment-552214334

**Comment by antony-jr** [comment]
Yep working on it. For the time being you could use the official tool.

**Comment by antony-jr** [comment]
The required changes are done but the upload script seems to avoid uploading more than two files. So it might take some time before you see the cli version. If released, it should be the same name as the GUI AppImage except all the characters will be lower case (i.e) ```appimageupdater*.AppImage```

**Comment by antony-jr** [comment]
The CLI tool is release here -> https://github.com/antony-jr/AppImageUpdater/releases/tag/continuous-cli
