### ISSUE TITLE
Please make it look more native on the desktop

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#25]
Hallo @antony-jr thanks for your great work on AppImageUpdater. :+1: 

One thing I am really less than thrilled about

> Material Design

I would not want to put AppImageUpdater into my Qt based desktop applications if it doesn't look like the rest of the application. Let's make AppImageUpdater look and feel "native" to the desktop, not like an "alien" piece coming from Android.

Thanks for your consideration!

**Comment by antony-jr** [comment]
@probonopd Yes, I've taken this into account but only the main application uses QML and Material Design. The standalone dialogs that you use in go-appimaged are still native.

I just thought that material design is good. Yes it does look a bit Android but I'm improvising. Let's keep this thread open, it will  be interesting to get feedback on material design. If it's not beneficial then **I might need to rewrite everything in native Qt but that will take a lot of time**.

**EDIT**: 

One feature you might be thrilled is that now the standalone dialogs uses libappimage to get the AppImage icon and name from the desktop file, This will make it more attractive. You might want to use the ```latest``` tag here(https://github.com/probonopd/go-appimage/blob/6249fabe78b8725307ba2fbcdc548b56dc70937d/src/appimaged/update.go#L38) if you want to use the v2.x 



https://user-images.githubusercontent.com/33930174/113411573-bccf0b00-93d3-11eb-9cb9-19a662ed6482.mp4

**Comment by probonopd** [comment]
Hello @antony-jr 

> The standalone dialogs that you use in go-appimaged are still native.

I was mainly referring to this screenshot:

![](https://user-images.githubusercontent.com/33930174/109507295-96603c00-7ac4-11eb-8249-534c6c44a157.png)

This looks not like the rest of FreeCAD. This looks like an Android application.

Are you saying that if FreeCAD builds in the Torrent-enabled updater, then it will not look like on the screenshot but will look more Qt native?

**Comment by antony-jr** [comment]
> Hello @antony-jr
> 
> > The standalone dialogs that you use in go-appimaged are still native.
> 
> I was mainly referring to this screenshot:
> 
> ![](https://user-images.githubusercontent.com/33930174/109507295-96603c00-7ac4-11eb-8249-534c6c44a157.png)
> 
> This looks not like the rest of FreeCAD. This looks like an Android application.
> 
> Are you saying that if FreeCAD builds in the Torrent-enabled updater, then it will not look like on the screenshot but will look more Qt native?

@probonopd I think you misunderstood, I was talking about this updater in that thread. **Yes, if FreeCAD integrates the updater into FreeCAD, it will use the native version only.(The native gui for torrent update is the same as the normal one you see in the standalone dialogs)** This is because we will be using the library and no source from this repo. Remember both are entirely different projects and has a different license. Particularly this one has LGPL v3 license because I tend to static compile with Qt sometimes to reduce the application size.

**Comment by probonopd** [comment]
OK, if the updater that will end up in applications looks native then I am happy :100:
