### ISSUE TITLE
Increase verbosity on the command line

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#3]
It would be nice if AppImageUpdater would print some verbose statements on the command line while it is working, e.g., when invoked with `-v` or `-verbose`, so that one could understand what it is trying to do (e.g., from which URLs it is trying to download).

**Comment by antony-jr** [comment]
its true by default , **Try** running it from terminal. Does that verbosity lack something? Please let me know.

**Comment by antony-jr** [comment]
``` -h ``` to get help on available commands!

**Comment by probonopd** [comment]
`me@host:~$ squashfs-root/AppRun ./appimagetool-x86_64.AppImage` is not outputting anything. E.g., it could output the `zsync|https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage.zsync` update information string it has found in the AppImage, or the parsed first field, then could say it does not know how to handle the "zsync" transport mechanism, etc.

**Comment by antony-jr** [comment]
got it 👍

**Comment by antony-jr** [comment]
This is also fixed in the latest release , if not please reopen! ❤️ 
**Ref**: https://github.com/antony-jr/AppImageUpdater/commit/8056e82c6f2107dc03049963e105f9c3c3029449
