### ISSUE TITLE
Updated file must also get the new name

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#5]
```
Downloads/AppImageUpdater-77e112e-x86_64.AppImage Downloads/Audacity-095ee91-x86_64.AppImage 
```

__Intended result__:

In addition to the original (old) file `Downloads/Audacity-095ee91-x86_64.AppImage`, there should be the updated (new) file `Downloads/<FILENAME_OF_THE_NEW_FILE>`.

__Actual result__:

![result](https://user-images.githubusercontent.com/2480569/34906045-165c4e02-f865-11e7-80c0-fad5e5cc2d9c.png)

```
me@host:~$ diff Downloads/Audacity-095ee91-x86_64.AppImage*
Binary files Downloads/Audacity-095ee91-x86_64.AppImage and Downloads/Audacity-095ee91-x86_64.AppImage.zs-old differ
```

Updated file must also get the new name, otherwise the file name is misleading.

**Comment by antony-jr** [comment]
hmm... no problem , but I think this will be a change in the **Bridge**.

**Comment by probonopd** [comment]
Wow, I am impressed, this looks like a straightforward change. Will there be a new AppimageUpdater to test?

**Comment by antony-jr** [comment]
Made very silly mistake  so the continous integration is broken , Please wait.

**Comment by antony-jr** [comment]
@probonopd continous build of **linuxdeployqt** is broken (can't get the latest AppImages ? ) , thats why my continous build is also broken!

**Comment by antony-jr** [comment]
@probonopd I cannot find any **assets** on github , do I need to compile it my self ?

**Comment by probonopd** [comment]
> @probonopd I cannot find any assets on github , do I need to compile it my self ?

Sorry, it's a bug, I am looking into it. Should be available again soon.
https://github.com/AppImage/AppImageKit/issues/612#issuecomment-357441159

**Comment by antony-jr** [comment]
@probonopd Build Succeded , Check the new release.
**NOTE:** The updater will automatically update itself but only the new version will have the update on renaming the files correctly. So test it out with other appimages.
