### ISSUE TITLE
Give clear message if GitHub Release does not have an AppImage

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#6]
The updater should give a clear message if GitHub Release does not have an AppImage

Test file:
[OldImageMagick-git.7a48608-x86_64.AppImage.zip](https://github.com/AppImage/AppImageUpdate/files/1451080/OldImageMagick-git.7a48608-x86_64.AppImage.zip)

For comparison, [AppImageUpdate](https://github.com/AppImage/AppImageUpdate) says:

```
me@host:~$ /isodevice/Applications/AppImageUpdate-185-1c72f3b-x86_64.AppImage OldImageMagick-git.7a48608-x86_64.AppImage 
AppImageUpdate version 1-alpha (commit 1c72f3b), build 185 built on 2018-01-03 16:41:48 UTC
Checking for updates...
Fetching release information for tag "continuous" from GitHub API.
GitHub API request failed!
Could not find any artifacts in release data. Please contact the author of the AppImage and tell them the files are missing on the releases page.
ZSync URL not available. See previous messages for details.
```

**Comment by antony-jr** [comment]
got it! 👍

**Comment by antony-jr** [comment]
this is not enough ?
```
QAIUpdateInformation::  "gh-releases-zsync|probonopd|ImageMagick|continuous|ImageMagick*-x86_64.AppImage.zsync"
AIUpdaterBridge:: github release link :: QUrl("https://api.github.com/repos/probonopd/ImageMagick/releases/tags/continuous")
AIUpdaterBridge:: network error ::  QNetworkReply::NetworkError(ContentNotFoundError)
```

**Comment by antony-jr** [comment]
@probonopd why does the **title** bar **icon** is not showing up ? The icon only shows up if I run it outside of the AppImage.

**Comment by antony-jr** [comment]
Try the new version , **The Updater** should update itself by now ?

**Comment by probonopd** [comment]
> this is not enough ?

```
QAIUpdateInformation
QAIUpdateInformation::  "gh-releases-zsync|probonopd|ImageMagick|continuous|ImageMagick*-x86_64.AppImage.zsync"
AIUpdaterBridge:: github release link :: QUrl("https://api.github.com/repos/probonopd/ImageMagick/releases/tags/continuous")
AIUpdaterBridge:: network error ::  QNetworkReply::NetworkError(ContentNotFoundError)
```

This looks good but I can't remember to have seen this when I tested originally.

**Comment by probonopd** [comment]
> @probonopd why does the title bar icon is not showing up ? The icon only shows up if I run it outside of the AppImage.

Good question, as per https://discourse.appimage.org/t/appimage-does-not-show-icon-in-task-bar/40/1 I would think that 

https://github.com/antony-jr/AppImageUpdater/blob/7690ab45ae06a2ac7585ec8e9ab6fe6315f5220a/AppImageUpdater.hpp#L84

should do it.

Reference:
https://github.com/JvanKatwijk/qt-dab/issues/69

**Comment by probonopd** [comment]
> Try the new version , The Updater should update itself by now ?

Indeed, seems to work :+1:

**Comment by probonopd** [comment]
As to the original topic of this issue, the text in the window still says "unknown network interruption" when in fact GitHub does not have an AppImage available.

**Comment by antony-jr** [comment]
okay then we might need more error codes to be generated from AppImageUpdaterBridge , check the available error codes here , https://antony-jr.github.io/AppImageUpdaterBridge/docs/AppImageUpdaterBridgeErrorCodes.html

**Comment by antony-jr** [comment]
@probonopd This issue is irrelevant now since all errors are emitted explicitly now , I just need some time to convert these error codes to human readable Message box which is a pain in the neck but I will finish it soon , The logging is good now , Try the new version!
