### ISSUE TITLE
"Updater" button does nothing

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdater#9]
"Updater" button in the bottom left seemingly does nothing when clicked. It is unclear what it is supposed to do as well, so maybe it can be removed. Let's simplify as much as possible.

**Comment by antony-jr** [comment]
it only get active when you are not in the main page

**Comment by probonopd** [comment]
Then maybe don't show it in the main page.

**Comment by antony-jr** [comment]
got it 👍
